name: Merge Automatizado
'on':
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize, edited, ready_for_review, reopened ]
    branches: [develop]
jobs:
  job_automerge:
    if: ${{ (github.event.label.name == 'automated') || contains(github.event.pull_request.title, '[Build_MR]') }}
    name: Ejecución Merge Automatizado
    needs: job_pruebas_automaticas
    runs-on: ubuntu-latest
    steps:
      - name: Ejecución Merge Automatizado
        id: merge-automatizado
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: ''
          MERGE_COMMIT_MESSAGE: "Merge automatico de: ${{ github.event.pull_request.title }}"
      - name: Retroalimentación del Merge
        if: steps.merge-automatizado.outputs.mergeResult == 'merged'
        run: >
          echo "Solicitud de Merge número (${{ steps.merge-automatizado.outputs.pullRequestNumber }}) fusionada con exito!"